### ISSUE TITLE
How to use libyaml_vendor in a CMakeLists.txt ?

### ISSUE THREAD

**Issue by ahcorde** [ros2/libyaml_vendor#10]
i have been checking how to include libyaml_vendor in a CMakeLists.txt but I have seen that we need to include `libyaml_vendor` and `yaml`:

```cmake
find_package(libyaml_vendor REQUIRED)
find_package(yaml REQUIRED)
```

Shouldn't it be just `libyaml_vendor` ?

**Comment by ahcorde** [comment]
@wjwwood what do you think about this?

**Comment by wjwwood** [comment]
Same thoughts as here: https://github.com/ros2/rcl_logging/issues/25#issuecomment-588547062

**Comment by hidmic** [comment]
@ahcorde shall we close?
