### ISSUE TITLE
Progress toward Quality Level 1

### ISSUE THREAD

**Issue by Blast545** [ros2/libyaml_vendor#11]
This issue tracks the progression of the package `libyaml_vendor` that have been deemed necessary for Quality Level 1. It follows the outline described in [REP 2004](https://github.com/ros-infrastructure/rep/blob/rep-2004/rep-2004.rst). 

* [x] Version Policy
    - `semver` according to the recommendation for ROS Core packages in the [ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#versioning).
* [x] Version >= 1.0.0
* [x] Change Control Process
    - Recommended guidelines for ROS Core packages in the [ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#package-requirements)
* [x] API and ABI stability within a ROS distribution
* [x] Vulnerability Disclosure Policy

Documentation
* [x] Per-feature documentation. 
    - (This package does not define its own features)
* [x] Per-item documentation in public API. 
    - (This package does not define its own API)
* [x] Declared set of licenses
* [x] Copyright statement in each source file
    - Checked with `ament_copyright`
* [x] Quality Declaration document

Testing:
* [x] System tests, which cover "features"
    - (Does not apply for vendored packages)
* [x] Tests covering public API
    - (Does not apply for vendored packages)
* [x] Code Coverage > 95%:
    - (Does not apply for vendored packages)
* [x] Performance tests.
    - (Does not apply for vendored packages)
* [x] Linters and Static Analysis:
  - * [x] Must have a code style and enforce it.
  - * [x] Must use static analysis tools where applicable: 
  -- Linters applied to package.xml and CmakeLists.txt files. See [Linters ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#linters)

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - None
* [ ] non-ROS dependencies are equivalent level 1
    - `libyaml` (QL 4)

Platform Support
* [x] Supports all tier 1 platforms as described in [REP-2000](https://www.ros.org/reps/rep-2000.html#support-tiers)

**Comment by ahcorde** [comment]
Update QD https://github.com/ros2/libyaml_vendor/pull/19

**Comment by chapulina** [comment]
`libyaml` and `libyaml_vendor` are level 1 on Foxy and Rolling. This issue can be closed (I don't have the power :zap: ).

**Comment by clalancette** [comment]
Closing.
