### ISSUE TITLE
failed to install rcl_yaml_param_parser package and finding libyaml_vendor

### ISSUE THREAD

**Issue by mkeyno** [ros2/libyaml_vendor#27]
I've tried to install ROS2 foxy from source to my ubuntu Linux, but at will stop to compile sources at the `rcl_yaml_param_parser package`

I've checked the installed libraries and find the `python3-yaml ` and 'libyaml-dev` already  installed 
```
Starting >>> rcl_yaml_param_parser
--- stderr: rcl_yaml_param_parser
CMake Error at CMakeLists.txt:7 (find_package):
  By not providing "Findlibyaml_vendor.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "libyaml_vendor", but CMake did not find one.

  Could not find a package configuration file provided by "libyaml_vendor"
  with any of the following names:

    libyaml_vendorConfig.cmake
    libyaml_vendor-config.cmake

  Add the installation prefix of "libyaml_vendor" to CMAKE_PREFIX_PATH or set
  "libyaml_vendor_DIR" to a directory containing one of the above files.  If
  "libyaml_vendor" provides a separate development package or SDK, be sure it
  has been installed.


---
Failed   <<< rcl_yaml_param_parser [1.43s, exited with code 1]
```
and finally, it affects rcl package
```
Starting >>> rcl
--- stderr: rcl
CMake Error at CMakeLists.txt:8 (find_package):
  By not providing "Findrcl_yaml_param_parser.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "rcl_yaml_param_parser", but CMake did not find one.

  Could not find a package configuration file provided by
  "rcl_yaml_param_parser" with any of the following names:

    rcl_yaml_param_parserConfig.cmake
    rcl_yaml_param_parser-config.cmake

  Add the installation prefix of "rcl_yaml_param_parser" to CMAKE_PREFIX_PATH
  or set "rcl_yaml_param_parser_DIR" to a directory containing one of the
  above files.  If "rcl_yaml_param_parser" provides a separate development
  package or SDK, be sure it has been installed.


---
Failed   <<< rcl [5.71s, exited with code 1]


```

**Comment by sloretz** [comment]
> I've checked the installed libraries and find the python3-yaml and 'libyaml-dev` already installed

Is `ros-foxy-libyaml-vendor` installed, or if you're building all of foxy then is `libyaml_vendor` in there too? If so, what happens when you `colcon build --packages-select libyaml_vendor`?

note to self, [libyaml_vendor is in the foxy ros2.repos file](https://github.com/ros2/ros2/blob/baee911943bf662c9947acc31ebebfc98397b596/ros2.repos#L218-L221)

**Comment by mkeyno** [comment]
@sloretz 
can't find it 
```
[2.933s] WARNING:colcon.colcon_core.package_selection:ignoring unknown package 'libyaml_vendor' in --packages-select

Summary: 0 packages finished [3.25s]

```

**Comment by sloretz** [comment]
>  can't find it

That's the problem. Did this step complete successfully? https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Development-Setup/#get-ros-2-code

I would recommend deleting the `src` folded of your workspace and re-downloading the foxy sources. If it completes successfully you should see a folder `src/ros2/libyaml_vendor/`.

This doesn't seem to be a bug in this repo, so I'll close the issue for now. I would recommend opening a question on https://answers.ros.org if there's further issues.
