### ISSUE TITLE
Fix cmake version or remove target_link_directories

### ISSUE THREAD

**Issue by norro** [ros2/libyaml_vendor#28]
In latest master, the cmake command `target_link_directories` is used, which is not available before cmake 3.13, see https://cmake.org/cmake/help/git-stage/command/target_link_directories.html
So either the `cmake_minimum_required` should be increased from currently 3.9 to >=3.13, or `target_link_directories` should be removed.

**Comment by clalancette** [comment]
> `target_link_directories` should be removed.

Thanks for the report.  Yeah, we should remove `target_link_directories` here, as we still aim to support systems with CMake 3.10.  @ahcorde can you take a look?

**Comment by ahcorde** [comment]
Fixed here https://github.com/ros2/libyaml_vendor/pull/29

**Comment by ahcorde** [comment]
PR is merged. I will close the issue. @norro feel free to reopen the issue if there is any related issue

**Comment by Jconn** [comment]
@ahcorde are there plans to backport this to foxy? Foxy does not build from source on systems with cmake < 3.13
