### ISSUE TITLE
Added support for Android

### ISSUE THREAD

**Issue by Theosakamg** [ros2/libyaml_vendor#3]
Failed build for Android : https://api.travis-ci.org/v3/job/389478345/log.txt

Pass many arguments for android build. ( Similar to https://github.com/ros2/poco_vendor/blob/f2f3b7a9cc67bb84ccf40db2ad08ef90add99357/CMakeLists.txt )

Fix in #2

**Comment by mikaelarguedas** [comment]
Fixed by #2
