### ISSUE TITLE
libyaml ignores cmake option BUILD_SHARED_LIBS=OFF

### ISSUE THREAD

**Issue by hannes09** [ros2/libyaml_vendor#42]
I have tried to compile a ros2 static stack

Turns out that the global cmake flag `BUILD_SHARED_LIBS=OFF` is ignorde by libyaml_vendor CMakeLists.txt.
So libyaml ends up as a shared library.

Can you set `BUILD_SHARED_LIBS=ON` only if `BUILD_SHARED_LIBS` was not set exlicit?

**Comment by clalancette** [comment]
> Can you set `BUILD_SHARED_LIBS=ON` only if `BUILD_SHARED_LIBS` was not set exlicit?

If you have time, please submit a pull request with this change.  We're happy to review it.

**Comment by allsey87** [comment]
Until this is fixed changing:
https://github.com/ros2/libyaml_vendor/blob/73c8ea6cec14474d9b256c61fc6a2d9af9e5dcbb/CMakeLists.txt#L27
to forward the `BUILD_SHARED_LIBS` seems to work fine:
```cmake
list(APPEND extra_cmake_args -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS})
```

**Comment by gavanderhoorn** [comment]
Ran into this myself, but was saved by the fact my toolchain file (via a custom *platform*) completely disables support for shared libraries (`GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS FALSE`).

It would indeed be nice if CMake would not be hard-coded to configure for a shared library version of `libyaml`.

**Comment by mjcarroll** [comment]
This issue pre-dates using `ament_cmake_vendor_package`.  I'm going to close it out.  Feel free to open another issue if the problem persists.
