### ISSUE TITLE
Forward CMake args to the ExternalProject build in a generic way

### ISSUE THREAD

**Issue by gavanderhoorn** [ros2/libyaml_vendor#56]
Issue #42 describes a specific case of the `ExternalProject(..)` call not forwarding CMake arguments to the child CMake configure phase (in that issue: `BUILD_SHARED_LIBS`).

The `CMakeLists.txt` in this repository has been extended several times to selectively pass specific arguments (such as `CMAKE_TOOLCHAIN_FILE`, `CMAKE_BUILD_TYPE`, etc). This required adding a boilerplate `if-defined-pass-value` construct for each variable. The latest addition would be #44, which wants to pass `BUILD_SHARED_LIBS` if set.

Would it perhaps be an idea to pass "all" arguments passed to CMake at configure time to the child CMake instance? There doesn't appear to be support for this in CMake proper, but approaches such as the one in [this SO Q&A](https://stackoverflow.com/questions/12021448) work around that:

<details><summary>Click to expand</summary>

```cmake
# MUST be done before call to 'project'
get_cmake_property(vars CACHE_VARIABLES)
foreach(var ${vars})
  get_property(currentHelpString CACHE "${var}" PROPERTY HELPSTRING)
    if("${currentHelpString}" MATCHES "No help, variable specified on the command line." OR "${currentHelpString}" STREQUAL "")
        # message("${var} = [${${var}}]  --  ${currentHelpString}") # uncomment to see the variables being processed
        list(APPEND CL_ARGS "-D${var}=${${var}}")
    endif()
endforeach()

...

project(...)

...

ExternalProject_Add(ext_proj
  ...
  CMAKE_ARGS ${CL_ARGS}
)
```

</details>

For `libyaml_vendor` specifically, this would make it possible to remove just about all `if(DEFINED ...) list(APPEND extra_cmake_args "-D...=${...}") endif()` sequences, cleaning up the `CMakeLists.txt`.

A quick test shows this works quite well.

One thing I wasn't sure about was that the 'outer' CMake invocation was passed a value for `CMAKE_INSTALL_PREFIX` by Colcon already, and that was also being forwarded. But [these lines](https://github.com/ros2/libyaml_vendor/blob/0c814892fe8c31aeb20688a8b43906aeefda015e/CMakeLists.txt#L88-L91) already configure that arg with a setting specific to `libyaml_vendor`.

However, last-setting-wins with CMake, so as long as the custom args passed come *after* the forwarded args, `CMAKE_INSTALL_PREFIX` and `INSTALL_INCLUDE_DIR` get the values hard-coded in the `ExternalProject(..)` call and things just work.

---

My main motivation is cross-compilation of this package. This often requires specific settings to be passed to CMake. While the toolchain file is correctly passed, anything not already handled by the top-level `CMakeLists.txt` here will not be, causing failed builds.

Transparently passing all command line args would help facilitate custom builds like cross-compilation.

**Comment by gavanderhoorn** [comment]
Just noticed the [cottsay/ament_vendor](https://github.com/ros2/libyaml_vendor/compare/cottsay/ament_vendor) branch.

The macro provided by `ament_cmake_vendor_package` seems [to also specifically check for a number of CMake variables/command line arguments](https://github.com/ament/ament_cmake/blob/5d3d6e97c8f706861f88ac36a1a730f6487dfec0/ament_cmake_vendor_package/cmake/ament_vendor.cmake#L175-L243).

**Comment by mjcarroll** [comment]
Since we have switched this package over to `ament_cmake_vendor_package`, I believe that this issue is resolved.  I'm going to close this out.  @gavanderhoorn feel free to re-open if you are still having issues cross compiling with `ament_cmake_vendor_package`
