### ISSUE TITLE
cmake files get installed to a weird location

### ISSUE THREAD

**Issue by rotu** [ros2/libyaml_vendor#6]
When installed with `apt install ros-dashing-libyaml-vendor`, a directory gets created with the following files:
```
$ls -1 /opt/ros/dashing/cmake
yamlConfig.cmake
yamlConfigVersion.cmake
yamlTargets.cmake
yamlTargets-none.cmake
```
If these need to be installed a second time (not sure if the dependency should be pulled from a system libyaml), they should probably instead be installed in the share directory:
```
$ ls -1 /opt/ros/dashing/share/libyaml_vendor/cmake
ament_cmake_export_libraries-extras.cmake
libyaml_vendorConfig.cmake
libyaml_vendorConfig-version.cmake
```

**Comment by hidmic** [comment]
I'm not sure I follow.

**Comment by hidmic** [comment]
Closing as this has been inactive for a long time (and it targets Dashing, so it may not even be applicable anymore). 

Feel free to re-open if needed @rotu.
